name: Chatwork
configs:
  Debug: debug
  Release: release
  Test: debug
options:
  bundleIdPrefix: jp.ooaysora
  defaultConfig: Release
  deploymentTarget:
    iOS: 16.4
  xcodeVersion: "16.0"
settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: L6Q4H7M3DB
packages:
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    version: 4.2.2
targets:
  Chatwork:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.ooaysora.Chatwork
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    sources:
      - path: Chatwork
    resources:
      - path: Chatwork/Assets.xcassets
      - path: Chatwork/Preview Content
    dependencies:
      - target: API
      - package: KeychainAccess
  ChatworkTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ChatworkTests
    dependencies:
      - target: Chatwork
  ChatworkUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ChatworkUITests
    dependencies:
      - target: Chatwork
  API:
    type: framework
    platform: iOS
    info:
      path: API/Info.plist
    sources:
      - path: API
    resources: []
    dependencies: []
  APITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: APITests
    dependencies:
      - target: API
